### ISSUE TITLE
What do you think about adding a Pascal compiler?

### ISSUE THREAD

**Issue by ghost** [rochus-keller/EiGen#4]
You could use this as the reference:

https://github.com/vtereshkov/xdp (for DOS)

https://github.com/vtereshkov/xdpw (for Windows)

https://github.com/vtereshkov/raylib-xdpw (example library binding)

**Comment by rochus-keller** [comment]
I have no such plans. Maybe I will add my forthcoming Micron compiler and my current Cparser version.
