### ISSUE TITLE
Is this fork of chibicc powerful enough to bootstrap muon?

### ISSUE THREAD

**Issue by ghost** [rochus-keller/EiGen#5]
https://github.com/muon-build/muon

**Comment by rochus-keller** [comment]
I didn't try, but it is likely that chibicc or cparser could compile muon, but Eigen has it's own calling convention, so all Posix calls would have to be specially treated, and there is no optimizer yet. I'm mostly interested in Eigen as a backend of my Micron language which I will use to implement operating systems; if the whole system is compiled with Eigen, then the different calling convention is no longer an issue, but quite some time will be required until I get there.
